"""Demo defect reports positioned around Skopje for seeding."""

SAMPLE_DEFECTS = [
    {
        "bus_number": "412",
        "type": "brakes",
        "priority": "high",
        "status": "inProgress",
        "description": "Кочниците реагираат бавно при сопирање на ниска брзина.",
        "lat": 41.9965,
        "lng": 21.4314,
        "hours_ago": 30,
    },
    {
        "bus_number": "305",
        "type": "electrical",
        "priority": "medium",
        "status": "newReport",
        "description": "Контролната табла трепка повремено додека возилото работи.",
        "lat": 42.0041,
        "lng": 21.4090,
        "hours_ago": 4,
    },
    {
        "bus_number": "118",
        "type": "doors",
        "priority": "low",
        "status": "resolved",
        "description": "Задната врата не се затвора целосно од прв обид.",
        "lat": 41.9890,
        "lng": 21.4450,
        "hours_ago": 120,
    },
    {
        "bus_number": "720",
        "type": "mechanical",
        "priority": "high",
        "status": "inProgress",
        "description": "Чудни звуци од моторот при забрзување над 40 km/h.",
        "lat": 42.0102,
        "lng": 21.4201,
        "hours_ago": 52,
    },
    {
        "bus_number": "233",
        "type": "lights",
        "priority": "medium",
        "status": "newReport",
        "description": "Предните светла се значително послаби од нормално.",
        "lat": 41.9920,
        "lng": 21.4015,
        "hours_ago": 70,
    },
    {
        "bus_number": "540",
        "type": "climate",
        "priority": "low",
        "status": "rejected",
        "description": "Греењето не работи во задниот дел од автобусот.",
        "lat": 41.9788,
        "lng": 21.4377,
        "hours_ago": 168,
    },
    {
        "bus_number": "401",
        "type": "bodywork",
        "priority": "low",
        "status": "newReport",
        "description": "Оштетена надворешна страница веднаш до предниот влез.",
        "lat": 42.0008,
        "lng": 21.4502,
        "hours_ago": 26,
    },
    {
        "bus_number": "612",
        "type": "other",
        "priority": "medium",
        "status": "inProgress",
        "description": "Седиштето кај излезот во средината е расклатено.",
        "lat": 41.9850,
        "lng": 21.4150,
        "hours_ago": 90,
    },
]
